[[language]]
name = "vala"
scope = "source.vala"
roots = []
comment-token = "//"
injection-regex = "vala"
file-types = ["vala"]
language-server = { command = "vala-language-server" }
indent = { tab-width = 2, unit = "  " }